format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipTelnet}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_TELNET_AUTHENTICATION_CONN_INFO}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Combo
    attributes: {id: TCPIP_TELNET_AUTH_CONFIG}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: (OBSOLETE) Build Time Authentication}
  - type: Integer
    attributes: {id: TCPIP_TELNET_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tcpipTelnet, value: '56'}
  - type: String
    attributes: {id: TCPIP_TELNET_PASSWORD}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: Microchip}
  - type: Integer
    attributes: {id: TCPIP_TELNET_SKT_RX_BUFF_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '330'}
  - type: Integer
    attributes: {id: TCPIP_TELNET_SKT_TX_BUFF_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '330'}
  - type: String
    attributes: {id: TCPIP_TELNET_USERNAME}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '316', y: '154', id: tcpipTelnet}
