format_version: v1.0
type: UniqueComponent
attributes: {id: tcpipIPv4}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TCPIP_IPV4_COMMANDS_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_IPV4_EXTERN_PACKET_PROCESS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_IPV4_FORWARD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Menu
    attributes: {id: TCPIP_IPV4_FORWARD_SETTING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TCPIP_IPV4_FRAGMENTATION}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Menu
    attributes: {id: TCPIP_IPV4_FRAGMENT_SETTING}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '59', y: '65', id: tcpipIPv4}
