configName: pic32mx_eth_sk
folderName: pic32mx_eth_sk
format_version: v1.0
frameworkPath: ..\..\..
processor: PIC32MX795F512L
projectName: pic32mx_eth_sk
settings:
  PackageFilter: aws_cloud;azure_rtos;bsp;core;core_apps_pic32mx;core_apps_pic32mz_ef;core_apps_sam_d5x_e5x;crypto;cryptoauthlib;cryptoauthlib_apps;crypto_apps_encrypt_decrypt;crypto_apps_large_hash;crypto_apps_speed_test;csp;csp_apps_pic32mx;csp_apps_pic32mz_ef;Devices;dev_packs;harmony-services;net;net_apps_pic32mx;net_apps_pic32mz;net_apps_sam_e5x;quick_docs;reference_apps;usb;usb_apps_device;usb_apps_host;wireless_apps_pic32cxbz2_wbz45;wireless_apps_winc1500;wireless_ble;wireless_pic32cxbz_wbz;wireless_system_pic32cxbz_wbz;wireless_wifi;wireless_zigbee
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.5.259\atdf\PIC32MX795F512L.atdf
