format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32MX_Ethernet_Starter_Kit_II, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '506', y: '34', id: BSP_PIC32MX_Ethernet_Starter_Kit_II}
