configName: pic32mx_eth_sk2
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: PIC32MX795F512L
projectName: ''
settings:
  PackageFilter: audio;aws_cloud;bootloader;bootloader_apps_can;bootloader_apps_ethernet;bootloader_apps_i2c;bootloader_apps_sdcard;bootloader_apps_serial_memory;bootloader_apps_uart;bootloader_apps_usb;bsp;classb_sam_e5x_d5x;core;core_apps_pic32mm;core_apps_pic32mx;core_apps_pic32mz_da;core_apps_pic32mz_ef;core_apps_pic32mz_w1;core_apps_sam_d21_da1;crypto;cryptoauthlib;cryptoauthlib_apps;crypto_apps_encrypt_decrypt;crypto_apps_large_hash;crypto_apps_speed_test;csp;csp_apps_pic32mm;csp_apps_pic32mx;csp_apps_pic32mz_da;csp_apps_pic32mz_ef;csp_apps_pic32mz_w1;csp_apps_sam_d21_da1;Devices;dev_packs;ethercat;expresslogic_threadx;gfx;gfx_apps;harmony-services;micrium_ucos3;motor_control;MPLAB-Harmony-Reference-Apps;net;net_10base_t1s;net_apps_pic32mx;net_apps_pic32mz;net_apps_sam_e70_v71;quick_docs;reference_apps;smartenergy;touch;usb;usb_apps_device;usb_apps_dual_role;usb_apps_host;usb_apps_multi_controller;wireless;wireless_apps_pic32mzw1_wfi32e01;wireless_apps_winc1500;wireless_system_pic32mzw1_wfi32e01;wireless_wifi;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.5.259\atdf\PIC32MX795F512L.atdf
